name: ðŸš€ Deploy

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 16.17.0
      BUILD_SOURCE_DIR: .
      BUILD_ARTIFACT_STAGING_DIR: build/
      BUILD_ARTIFACT_DESTINATION_DIR: .
      HOST_SERVER: s176.webhostingserver.nl
      SENTRY_ORG: sa-proto
      SENTRY_PROJECT: sa-proto-website
    steps:
      - name: ðŸ›Žï¸ Checkout project
        uses: actions/checkout@v2

# Idk waar dit voor is
#       - name: ðŸ” Get Node version
#         id: nvm
#         run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)

      - name: ðŸ–±ï¸ Set Node v${{ steps.nvm.outputs.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: ðŸ“¥ Installing backend dependencies
        run: npm ci --ignore-scripts

      - name: ðŸ“¥ Installing frontend dependencies
        run: cd ./vue-remote && npm ci --ignore-scripts

      - name: ðŸ”¨ Building frontend
        run: npm run build

# hebben we denk ik niet nodig, atleast voor nu
#      - name: ðŸ“ Create Sentry release
#        uses: getsentry/action-release@v1
#        env:
#          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
#          SENTRY_ORG: ${{ env.SENTRY_ORG }}
#          SENTRY_PROJECT: ${{ env.SENTRY_PROJECT }}
#        with:
#          environment: production

      - name: ðŸ“ Create build directory
        run: mkdir ${{ env.BUILD_ARTIFACT_STAGING_DIR }}

      - name: ðŸ—„ï¸ ZIP Build
        uses: TheDoctor0/zip-release@0.6.1
        with:
          filename: ${{ env.BUILD_ARTIFACT_STAGING_DIR }}build.zip
          path: ${{ env.BUILD_SOURCE_DIR }}
          exclusions: 'vue-remote/* build/* ssl/*'

      - name: âž— Calculate checksum
        run: openssl md5 ${{ env.BUILD_ARTIFACT_STAGING_DIR }}build.zip | cut -d" " -f2 > ${{ env.BUILD_ARTIFACT_STAGING_DIR }}checksum.txt

# to be configured later
#       - name: ðŸ“‚ Sync files
#         uses: SamKirkland/FTP-Deploy-Action@4.3.2
#         with:
#           server: ${{ env.HOST_SERVER }}
#           username: ${{ secrets.FTP_USER }}
#           password: ${{ secrets.FTP_PASSWORD }}
#           local-dir: ${{ env.BUILD_ARTIFACT_STAGING_DIR }}
#           server-dir: ${{ env.BUILD_ARTIFACT_DESTINATION_DIR }}